package fr.univtln.bruno.starter.ai.v1;

import jakarta.inject.Inject;
import jakarta.ws.rs.*;
import jakarta.ws.rs.core.MediaType;

/**
 * REST resource exposing a simple AI-powered travel assistant (V1).
 *
 * <p>This version is intentionally minimal:
 * <ul>
 *   <li>No structured Java model (no TravelPlan DTO)</li>
 *   <li>No JSON parsing</li>
 *   <li>The AI returns JSON as raw text</li>
 * </ul>
 *
 * <p>Goal: understand how an LLM can generate structured-looking output,
 * before introducing proper Java mapping in later versions.
 */
@Path("/api/v1/travel")
@Produces(MediaType.TEXT_PLAIN)
public class MyAIResource {

    /**
     * AI service used to generate travel plans as JSON text.
     */
    @Inject
    MyAiService aiService;

    /**
     * Calls the LLM and returns a travel plan as raw JSON text.
     *
     * <p>The response is NOT validated or parsed into Java objects.
     * It is returned exactly as generated by the model.
     *
     * @param topic travel destination or theme (e.g. "Paris", "Japan")
     * @param days number of days for the itinerary (default = 3)
     * @return JSON string generated by the AI model
     *
     * @throws BadRequestException if topic is missing or empty
     */
    @GET
    public String plan(
            @QueryParam("topic") String topic,
            @QueryParam("days") @DefaultValue("3") int days
    ) {
        if (topic == null || topic.isBlank()) {
            throw new BadRequestException("topic cannot be empty");
        }

        return aiService.plan(topic, days);
    }
}