quarkus.http.host=0.0.0.0

############################################################
# LOGGING (DEBUG - KEEP DURING LEARNING)
############################################################
quarkus.langchain4j.log-requests=true
quarkus.langchain4j.log-responses=true
quarkus.langchain4j.log-messages=true

############################################################
# OLLAMA BASE
############################################################
quarkus.langchain4j.ollama.base-url=http://localhost:11434


############################################################
# DEFAULT CHAT MODEL
############################################################
#quarkus.langchain4j.ollama.chat-model.model-name=qwen3:1.7b
quarkus.langchain4j.ollama.chat-model.model-id=qwen3:4b

# IMPORTANT FOR SMALL MODEL STABILITY
#quarkus.langchain4j.ollama.chat-model.temperature=0.2
#quarkus.langchain4j.ollama.chat-model.top-p=0.8

#quarkus.langchain4j.ollama.chat-model.format=json

# OUTPUT LENGTH (VERY IMPORTANT)
#quarkus.langchain4j.ollama.chat-model.num-predict=1200


############################################################
# GLOBAL TIMEOUT (IMPORTANT FOR OLLAMA)
############################################################
quarkus.langchain4j.timeout=2m

# Enable message-window memory (recommended default for chat agents)
#quarkus.langchain4j.chat-memory.type=message-window

# Control context size
quarkus.langchain4j.chat-memory.memory-window.max-messages=20