package fr.univtln.bruno.starter.ai;

import org.eclipse.microprofile.openapi.annotations.media.Schema;

import java.util.List;

/**
 * Data model representing a structured AI-generated travel plan.
 *
 * <p>This record is used as a DTO (Data Transfer Object) between:
 * <ul>
 *   <li>the AI service (LangChain4j output)</li>
 *   <li>the REST API layer</li>
 *   <li>the OpenAPI documentation</li>
 * </ul>
 *
 * <p>It demonstrates a key Quarkus principle:
 * using simple immutable data structures for API contracts.
 */
@Schema(description = "The comprehensive generated travel itinerary")
public record TravelPlan(

        /**
         * Main destination of the travel plan (e.g., Paris, Tokyo).
         * This field is also exposed in OpenAPI documentation.
         */
        @Schema(example = "Paris")
        String destination,

        /**
         * Number of days covered by the itinerary.
         */
        @Schema(example = "3")
        int days,

        /**
         * List of daily itineraries generated by the AI.
         * Each entry represents one day of the trip.
         */
        List<DayPlan> itinerary
) {

    /**
     * Represents a single day in the travel itinerary.
     *
     * <p>This nested record shows how Quarkus DTOs can be composed
     * in a clean and hierarchical way.
     */
    @Schema(description = "Daily breakdown of activities and meals")
    public record DayPlan(

            /**
             * Day index in the itinerary (starting from 1).
             */
            @Schema(example = "1")
            int day,

            /**
             * List of activities planned for the day.
             *
             * <p>These are generated by the AI and constrained by the system prompt
             * (e.g., sightseeing, museum visits, etc.).
             */
            List<String> activities,

            /**
             * Suggested main meal or food experience for the day.
             */
            @Schema(example = "Croissant and Cafe au lait")
            String food
    ) {}
}